version: '3.7'

services:
  mrfreeze_nora:
    build:
      context: './MrFreeze/'
      dockerfile: Dockerfile
      args:
        - userid=${DCUSERID}
        - groupid=${DCGRPID}
    image: 'mrfreeze_nora'
    container_name: 'mrfreeze_nora'
    volumes:
      - ${DCDEVDIR}/config/:/home/lig/conf
      - ${DCDATADIR}/logs/lig:/home/lig/logs
    working_dir: /home/lig/Codes/MrFreeze/
    command: ["python", "Nora.py", "-l", "/home/lig/logs/nora.log", "-c", "/home/lig/conf/mrfreeze.conf", "-p", "/home/lig/conf/passwords.conf", "--debug"]
    networks:
      - default
    user: ${DCUSERID}:${DCGRPID}
    dns:
      - 10.11.131.100
    restart: always

networks:
    default:
        external: true
        name: ligDockernetPub
