FROM ligbase

USER root
# Add the non-free repository first so we can get the nonfree MIBs
# 
# Should find out a way to just get the debian release version automagically
RUN DEBIAN_RELEASE=buster && \
    # Adding non-free repo for netperf
    echo "deb http://deb.debian.org/debian ${DEBIAN_RELEASE} non-free" > \
        /etc/apt/sources.list.d/debian-non-free.list && \
    apt-get -qq update && \
    apt-get -y install snmp libsnmp-dev snmp-mibs-downloader \
                       libffi-dev smitools libsmi2-dev 

RUN pip install snimpy

USER lig
RUN mkdir /home/lig/.snmp && mkdir /home/lig/.snmp/mibs
COPY --chown=lig:lig ./mibs/* /home/lig/.snmp/mibs/

WORKDIR /home/lig/Codes/
COPY --chown=lig:lig ./DataServants ./DataServants

# Dump us into an iPython shell if there's no
#   actual command issued to start a LIG code
USER lig
WORKDIR /home/lig/
CMD ["ipython"]
