version: '3.7'

services:
  iago:
    build:
      context: '.'
      dockerfile: Dockerfile-dataservants
    image: 'dataservants'
    container_name: 'iago'
    volumes:
      - ${DCDEVDIR}/config/:/home/lig/conf
      - ${DCDATADIR}/logs/lig:/home/lig/logs
    working_dir: /home/lig/Codes/DataServants/
    command: ["python", "Iago.py", "-l", "/home/lig/logs/iago.log", "-c", "/home/lig/conf/iago.conf", "-p", "/home/lig/conf/passwords.conf", "--debug"]
    networks:
      - default
    user: ${DCUSERID}:${DCGRPID}
    restart: always
    dns:
      - 10.11.131.100

  alfred:
    image: 'dataservants'
    container_name: 'alfred'
    volumes:
      - ${DCDEVDIR}/config/:/home/lig/conf
      - ${DCDATADIR}/logs/lig:/home/lig/logs
    working_dir: /home/lig/Codes/DataServants/
    command: ["python", "Alfred.py", "-l", "/home/lig/logs/alfred.log", "-c", "/home/lig/conf/alfred.conf", "-p", "/home/lig/conf/passwords.conf", "--extraPings", "/home/lig/conf/alfred_extraPings.conf", "--debug"]
    networks:
      - default
    user: ${DCUSERID}:${DCGRPID}
    restart: always
    dns:
      - 10.11.131.100

  abu:
    image: 'dataservants'
    container_name: 'abu'
    volumes:
      - ${DCDEVDIR}/config/:/home/lig/conf
      - ${DCDATADIR}/logs/lig:/home/lig/logs
    working_dir: /home/lig/Codes/DataServants/
    command: ["python", "Abu.py", "-l", "/home/lig/logs/abu.log", "-c", "/home/lig/conf/abu.conf", "-p", "/home/lig/conf/passwords.conf", "--debug"]
    networks:
      - default
    user: ${DCUSERID}:${DCGRPID}
    restart: always
    dns:
      - 10.11.131.100

    #  radia:
    #    image: 'dataservants'
    #    container_name: 'radia'
    #    volumes:
    #      - ${DCDEVDIR}/config/:/home/lig/conf
    #      - ${DCDATADIR}/logs/lig:/home/lig/logs
    #    working_dir: /home/lig/Codes/DataServants
    #    command: ["python", "Radia.py", "-l", "/home/lig/logs/radia.log", "-c", "/home/lig/conf/radia.conf", "-p", "/home/lig/conf/passwords.conf", "--debug"]
    #    networks:
    #      - default
    #    user: ${DCUSERID}:${DCGRPID}
    #    restart: always


networks:
    default:
        # This means that the network is/was created elsewhere (MonTools)
        external: true
        name: ligDockernetPub
